server:
  port: 8383
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB
  datasource:
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-password: cwm1134128812
        login-username: ccwme
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false